language: python
install:
  python -m pip install bson
  pip install pymongo
  pip install dnspython
  pip install python-dotenv
  pip install pytest-dotenv
  pip install cryptography

script: pytest backend/sampleTest.py