language: python

before-install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  
install:
  - pip install bson
  - pip install pymongo
  - pip install dnspython
  - pip install python-dotenv
  - pip install pytest-dotenv
  - pip install cryptography

script: pytest backend/sampleTest.py