language: python

before-install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
  - pip3 uninstall bson
  - pip3 uninstall pymongo
  - pip3 install pymongo
  - pip3 install dnspython
  - pip3 install python-dotenv
  - pip3 install pytest-dotenv
  - pip3 install cryptography

script: pytest backend/sampleTest.py